/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Don' at '5/2/16 12:05 PM' with Gradle 2.13
 *
 * @author Donald Trummell, @date 5/2/16 12:05 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
