import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'dtrumme' at '5/2/16 12:11 PM' with Gradle 2.13
 *
 * @author dtrumme, @date 5/2/16 12:11 PM
 */
public class LibraryTest2 {
    @Test public void testSomeLibraryMethod2() {
        Library classUnderTest = new Library2();
        assertTrue("someLibraryMethod2 should return 'true'", classUnderTest.someLibraryMethod2());
    }
}
