package don.demo.generator;

import java.io.Serializable;
import java.util.List;
import java.util.Map.Entry;

/**
 * Builds list of matching inputs and output under corresponding base
 * directories
 * 
 * @author dtrumme
 */
public interface InputOutputBuilder extends Serializable {

    /**
     * Match input and output path entries; a single asterisk in the output
     * means copy from the input
     * 
     * @param srcDir
     *            base directory for source/input templates
     * @param templateList
     *            a list of template files under the <code>srcDir</code>
     * @param dstDir
     *            base directory destination for generated output files
     * @param generatedFileList
     *            a list of output files generated by the templates
     * @param useSrcDir
     *            if true, factor source-dir into input (template) path, else
     *            ignore
     * 
     * @return list of matched input-output pairs
     */
    public abstract List<Entry<String, String>> createPairedList(
            final String srcDir, final String[] templateList,
            final String dstDir, final String[] generatedFileList,
            final boolean useSrcDir);
}