/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dtrumme' at '5/2/16 12:11 PM' with Gradle 2.13
 *
 * @author dtrumme, @date 5/2/16 12:11 PM
 */
public class Library2 {
    public boolean someLibraryMethod2() {
        return true;
    }
}
