/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dtrumme' at '5/2/16 11:45 AM' with Gradle 2.13
 *
 * @author dtrumme, @date 5/2/16 11:45 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
