-- hive_vars.hql
--
-- Defines Hive variables used by the Hive query. An overview of Hive variables is found at
-- https://cwiki.apache.org/confluence/display/Hive/LanguageManual+VariableSubstitution.
--
<#-- Hive variable definition generated by Freemarker -->
--Generation date: Run date: @@{.now}

set tbl_prefix=@@{GEN_env_prefix};
set dbname=<#if GEN_target == "PRODUCTION">RAW_SALES<#else>RAW_SALES_SAMPLE</#if>;
set base_source_table_name=@@{GEN_src_tbl};
set source_table=${tbl_prefix}_${base_source_table_name};
set base_target_table_name=@@{GEN_tgt_tbl};
set target_table=${tbl_prefix}_${base_source_table_name};

set prod_brands="CHEVY", "FORD", "TOYOTA", "LEXUS", "HONDA", "BMW", "VW";
set nonprod_brands="CHEVY", "TOYOTA";
set brand_list=<#if GEN_target == "PRODUCTION">${prod_brands}<#else>${nonprod_brands}</#if>;
