package don.demo.generator;

import java.io.Serializable;
import java.util.List;
import java.util.Map.Entry;

/**
 * Builds list of matching inputs and output under corresponding base
 * directories
 * 
 * @author Donald Trummell
 * 
 *         Copyright (c) 2016. Donald Trummell. All Rights Reserved. Permission
 *         to use, copy, modify, and distribute this software and its
 *         documentation for educational, research, and not-for-profit purposes,
 *         without fee and without a signed licensing agreement, is hereby
 *         granted, provided that the above copyright notice, and this
 *         paragraph, appear in all copies, modifications, and distributions.
 *         Contact dtrummell@gmail.com for commercial licensing opportunities.
 */
public interface InputOutputBuilder extends Serializable
{

    /**
     * Match input and output path entries; a single asterisk in the output
     * means copy from the input
     * 
     * @param srcDir
     *            base directory for source/input templates
     * @param templateList
     *            a list of template files under the <code>srcDir</code>
     * @param dstDir
     *            base directory destination for generated output files
     * @param generatedFileList
     *            a list of output files generated by the templates
     * @param useSrcDir
     *            if true, factor source-dir into input (template) path, else
     *            ignore
     * 
     * @return list of matched input-output pairs
     */
    public abstract List<Entry<String, String>> createPairedList(final String srcDir, final String[] templateList,
            final String dstDir, final String[] generatedFileList, final boolean useSrcDir);
}